----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:14:04,242

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:14:52,195

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:14:52,512

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:14:55,900

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:14:56,208

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:19:20,776

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1393
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:19:36,433

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:19:36,739

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:20:59,881

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:21:00,195

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:24:17,455

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:24:17,768

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:25:25,199

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1393
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:26:01,752

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:26:02,058

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:26:08,450

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:26:08,761

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:42:03,311

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:42:03,629

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:43:43,711

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:44:05,747

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:44:06,052

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:44:52,998

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:44:53,312

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:46:13,431

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:46:13,730

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:48:29,803

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:48:30,120

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:49:02,473

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:49:02,783

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:50:23,924

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:50:24,226

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:50:52,478

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:50:52,782

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:51:29,314

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:51:29,622

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:52:24,062

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1393
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:52:25,799

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1393
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:52:44,232

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /ec2
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:52:44,232

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2 HTTP/1.1" 404 2176
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:55:49,176

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:55:52,137

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /ec2
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:55:52,138

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /container
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:55:52,139

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2 HTTP/1.1" 404 2176
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:55:52,139

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container HTTP/1.1" 404 2194
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:59:23,764

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:59:24,067

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:59:32,408

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /ec2
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:59:32,410

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /container
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:59:32,410

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2 HTTP/1.1" 404 2176
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 03:59:32,410

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container HTTP/1.1" 404 2194
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 03:59:37,158

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:00:53,572

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/settings.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:00:53,880

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:01:15,942

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:01:16,245

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:01:30,008

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/urls.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:01:30,311

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:01:34,284

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2 HTTP/1.1" 301 0
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 04:01:34,289

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Not Found: /container
----------------------------------------------------------------------------------------------------
[WARNING] - 2020-06-13 04:01:34,289

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container HTTP/1.1" 404 2194
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 04:01:34,393

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/log.py line: 228

Internal Server Error: /ec2/
Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 37, in query
    logger.error("".join(traceback.format_list()))
TypeError: format_list() missing 1 required positional argument: 'extracted_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 27, in query
    if target == "": return self.__queryAll()
  File "/root/awstest/awstest/ec2/ec2.py", line 23, in __queryAll
    raise e
  File "/root/awstest/awstest/ec2/ec2.py", line 20, in __queryAll
    self.query(target)
  File "/root/awstest/awstest/ec2/ec2.py", line 50, in query
    logger.error("".join(traceback.format_list()))
TypeError: format_list() missing 1 required positional argument: 'extracted_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/views.py", line 13, in get
    response = ec2.query()
  File "/root/awstest/awstest/ec2/ec2.py", line 50, in query
    logger.error("".join(traceback.format_list()))
TypeError: format_list() missing 1 required positional argument: 'extracted_list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib64/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "/root/awstest/awstest/ec2/views.py", line 16, in get
    logger.error("".join(traceback.format_list()))
TypeError: format_list() missing 1 required positional argument: 'extracted_list'
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 04:01:34,393

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 500 14939
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:02:31,089

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:12,651

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/ec2.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:12,961

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:26,713

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/container.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:27,018

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:40,763

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:41,069

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:43,413

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/container/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:43,720

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:53,317

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/ec2/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:09:53,629

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:06,329

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 222

/root/awstest/awstest/awstest/views.py changed, reloading.
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:06,633

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:40,018

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET / HTTP/1.1" 200 1818
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:45,115

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container HTTP/1.1" 301 0
----------------------------------------------------------------------------------------------------
[ERROR] - 2020-06-13 04:10:45,116

Source log file: /root/awstest/awstest/ec2/ec2.py line: 37

Traceback (most recent call last):
  File "/root/awstest/awstest/ec2/ec2.py", line 33, in query
    self.response[target] = json.loads(body)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:45,117

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /ec2/ HTTP/1.1" 200 456
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:10:45,205

Source log file: /usr/local/lib64/python3.6/site-packages/django/core/servers/basehttp.py line: 157

"GET /container/ HTTP/1.1" 200 61
----------------------------------------------------------------------------------------------------
[INFO] - 2020-06-13 04:19:26,082

Source log file: /usr/local/lib64/python3.6/site-packages/django/utils/autoreload.py line: 598

Watching for file changes with StatReloader
